### ISSUE TITLE
[EPIC] - New images management system

### ISSUE THREAD

**Issue by Oksydan** [Oksydan/falcon#229]
### Summary

TODO:
 - [ ] - https://github.com/Oksydan/falcon/issues/228
 - [ ] - https://github.com/Oksydan/falcon/issues/227
 - [ ] - https://github.com/Oksydan/falcon/issues/226
 - [ ] - https://github.com/Oksydan/falcon/issues/195
 - [ ] - https://github.com/Oksydan/falcon/issues/194

### Feature target required module/theme

is_themecore

### Drawbacks

N/A
